# =============================================================================
# UYS Reference Manager Service Configuration
# =============================================================================

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: reference-manager
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.cloud.stream.autoconfigure.StreamAutoConfiguration
  
  # =============================================================================
  # DATABASE CONFIGURATION (H2 In-Memory for Development)
  # =============================================================================
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # =============================================================================
  # JPA CONFIGURATION
  # =============================================================================
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 50
    open-in-view: false
  
  # =============================================================================
  # LIQUIBASE CONFIGURATION (DISABLED FOR DEVELOPMENT)
  # =============================================================================
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${spring.profiles.active}

# =============================================================================
# MANAGEMENT & MONITORING
# =============================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
  info:
    env:
      enabled: true
    git:
      mode: full

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level:
    com.uys.reference: INFO
    org.springframework.cloud.stream: WARN
    org.springframework.data.redis: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/reference-manager.log
    max-size: 100MB
    max-history: 30

# =============================================================================
# H2 CONSOLE CONFIGURATION
# =============================================================================
h2:
  console:
    enabled: true
    path: /h2-console

# =============================================================================
# SPRINGDOC OPENAPI CONFIGURATION
# =============================================================================
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    filter: true
    doc-expansion: none
    default-models-expand-depth: 3
    default-model-expand-depth: 3
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: true
  group-configs:
    - group: 'reference-data'
      display-name: 'Reference Data APIs'
      paths-to-match: '/**'
    - group: 'airline'
      paths-to-match: '/airlines/**'
      display-name: 'Airline Management'
    - group: 'aircraft'  
      paths-to-match: '/aircraft/**'
      display-name: 'Aircraft Management'
    - group: 'station'
      paths-to-match: '/stations/**'
      display-name: 'Station Management'
  servers:
    - url: http://localhost:8080/api
      description: Development server
