version: '3.8'

services:
  # =============================================================================
  # DATABASE SERVICES
  # =============================================================================
  mysql:
    image: mysql:8.0
    container_name: uys-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: uys_reference
      MYSQL_USER: uys_user
      MYSQL_PASSWORD: uys_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - uys-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  postgresql:
    image: postgres:15-alpine
    container_name: uys-postgresql
    environment:
      POSTGRES_DB: uys_archive
      POSTGRES_USER: uys_user
      POSTGRES_PASSWORD: uys_password
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./infra/postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - uys-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uys_user -d uys_archive"]
      timeout: 20s
      retries: 10

  # =============================================================================
  # CACHE SERVICE
  # =============================================================================
  redis:
    image: redis:7-alpine
    container_name: uys-redis
    command: redis-server --requirepass uys-redis-password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uys-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 20s
      retries: 10

  # =============================================================================
  # MESSAGE BROKER
  # =============================================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: uys-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - uys-network
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
      timeout: 20s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: uys-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: uys-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://uys-kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    ports:
      - "9092:9092"
      - "9101:9101"
    networks:
      - uys-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      timeout: 20s
      retries: 10

  # =============================================================================
  # MONITORING SERVICES
  # =============================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: uys-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - uys-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      timeout: 20s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    container_name: uys-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - uys-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      timeout: 20s
      retries: 10

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  mysql_data:
  postgresql_data:
  redis_data:
  grafana_data:

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  uys-network:
    driver: bridge